# Generated by Django 4.2.3 on 2023-07-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bid',
            new_name='book_id',
        ),
    ]
